# Generated by Django 3.2.5 on 2023-12-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.TextField(),
        ),
    ]
