# Generated by Django 4.2.7 on 2023-11-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0002_customusers_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='confirmation_code',
        ),
    ]
