# Generated by Django 3.2.5 on 2023-12-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0006_customusers_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='avatar',
            field=models.TextField(blank=True),
        ),
    ]
