# Generated by Django 3.2.5 on 2023-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0007_alter_customusers_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
