# Generated by Django 4.2.7 on 2023-11-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'ordering': ['types'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фотки')),
                ('recept', models.TextField()),
                ('category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='dishesls.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еды',
                'ordering': ['name'],
            },
        ),
    ]
